version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    container_name: "backend"
    build:
      # velog directory를 root로 사용
      context: ./backend
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - './backend:/backend'
      - '/backend/node_modules'
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: "mysql"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - "3306:3306"
    env_file:
      - ./.env.prod.db
volumes:
  mysql_data: